services:
  app:
    build:
      context: .
    container_name: escuela_app
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: escuela_db
      DB_USER: escuela_user
      DB_PASS: 123456
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: escuela_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: escuela_db
      MYSQL_USER: escuela_user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root123456
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot123456"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql
      - ./database/escuela_db_export.sql:/docker-entrypoint-initdb.d/01-escuela_db.sql:ro
      - ./database/phpmyadmin_setup.sql:/docker-entrypoint-initdb.d/02-phpmyadmin.sql:ro

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: escuela_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123456
      UPLOAD_LIMIT: 64M
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/conf.d/config.user.inc.php:ro
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
